### ISSUE TITLE
codeSuggestionsFromComments

### ISSUE THREAD

**Issue by scottlet** [sturdy-dev/codeball-action#188]
Hi,

I'm trying to get `codeSuggestionsFromComments` to work. The documentation is a little confusing as to what it is supposed to do, but I was expecting it would leave comments with code suggestions, is this the case?

If it's not, that's fine. 

If it is the case, then what do I need to do to get it to work? do you have any examples?

I've included it as such:

```
      - name: Codeball
        uses: sturdy-dev/codeball-action@v2
        with:
          codeSuggestionsFromComments: "true"
          approvePullRequests: "true"
          labelPullRequestsWhenApproved: "true"
          labelPullRequestsWhenReviewNeeded: "false"
          failJobsWhenReviewNeeded: "false"
          GITHUB_TOKEN: ${{ secrets.CODEBALL_GITHUB_TOKEN }}
```
in my yml file. Codeball seems to run OK and label the PR correctly but I don't get anything referring to codeSuggestionsFromComments in the output of the run, there's no mention of it running `suggester` at all
