### ISSUE TITLE
Codeball check fails if PR is approved

### ISSUE THREAD

**Issue by volodya-lombrozo** [sturdy-dev/codeball-action#195]
We are using `codeball-action` in our project:
```yaml
name: codeball
on:
  pull_request: {}
  pull_request_review_comment:
    types: [created, edited]
jobs:
  codeball_job:
    runs-on: ubuntu-20.04
    name: codeball
    steps:
      - uses: sturdy-dev/codeball-action@v2
        with:
          # For all configuration options see https://github.com/sturdy-dev/codeball-action/blob/v2/action.yml
          approvePullRequests: "true"
          labelPullRequestsWhenApproved: "true"
          labelPullRequestsWhenReviewNeeded: "false"
          failJobsWhenReviewNeeded: "false"
```

Every time `codeball` adds the `codeball:approved` label to a PR, we encounter the following error:
```sh
Error: Error: failed to create review HttpError: Resource not accessible by integration
[50](https://github.com/objectionary/eo/actions/runs/4938370500/jobs/8828046747?pr=2055#step:2:55)
Error: failed to create review HttpError: Resource not accessible by integration
```

You can see full logs in the next checks:
- https://github.com/objectionary/eo/actions/runs/4938370500/jobs/8828046747?pr=2055
- https://github.com/objectionary/eo/actions/runs/4894606932/jobs/8739056126?pr=2051

Issue comes from: https://github.com/objectionary/eo/issues/2056
